### ISSUE TITLE
Production API Key

### ISSUE THREAD

**Issue by antoinejaussoin** [sergiop/react-giphy-searchbox#25]
Hi,

First of all, thanks for this library, I'm using it on my retrospective tool (https://github.com/antoinejaussoin/retro-board/tree/v3) and it works like a charm.

I have a question though: how do you get a production API key? Following [Giphy's doc](https://developers.giphy.com/docs/sdk#verification), you need to get some `giphyRandomId` variable that should be set to the `window` object, which is not the case when using your component. How did you manage to solve this issue?

Many thanks!

**Comment by sergiop** [comment]
Hi @antoinejaussoin, I'm glad to head my simple library has helped you.

Concerning your issue, I have to admit I've never heard about this `giphyRandomId`. I quickly checked out my Giphy's dev account and I discovered that now you can create a new Apps using [Giphy's API](https://developers.giphy.com/docs/api/) and the new [Giphy's SDK](https://developers.giphy.com/docs/sdk#web). The SDK adds the production request process you are talking about.

If you use this library, which is based on the **Giphy's API**, you need to create a proper App, choosing the one on the right (see following image).

<p align="center">
<img width="250" alt="Schermata 2020-04-21 alle 00 11 14" src="https://user-images.githubusercontent.com/2235134/79804630-b67f8480-8364-11ea-8306-6e367fc4f832.png">
</p>

You'll find that the production request process is more simple and totally manual. It's basically a form where they ask you to provide some info on your application is using their API.

I known... sooner or later I'll have to move this library to Giphy's SDK, but it's not currently on my priority list. 😉

Let me know if this solves your issue.

**Comment by antoinejaussoin** [comment]
I can't believe I've been that stupid :) I created an SDK app weeks ago, and was trying to activate that, without realising that API app were different.

Thanks so much!
