### ISSUE TITLE
Specify a hundred percent width to the component

### ISSUE THREAD

**Issue by SouroucheB** [sergiop/react-giphy-searchbox#38]
Hi,

I was trying to build myself a giphy component like you did in React. So first, thanks.
But I had also a question. I can't figure out where I can specify a hundred percent container width since that sounds like the very first step to a responsive component for me.

Can you help me please ?

Thanks in advance.
Sourouche

**Comment by sergiop** [comment]
Hi, @SouroucheB reading what you wrote it seems you are at the very beginning of the thing. It's not simple to give you advice without knowing your project background. An HTML block element, like a `<div>` is per definition 100% width, so your question sounds a little bit strange, but probably I'm not understanding the point. Anyway, you need to work with CSS styles, take a look at `flexbox` properties, they can be useful for your purposes.
