### ISSUE TITLE
CSS Modules cannot be imported from within node_modules

### ISSUE THREAD

**Issue by Asif-chohan** [sergiop/react-giphy-searchbox#45]
I'm using react-giphy-searchbox with Next.js and Typescript. After installing the lib, the following error is appearing on the screen.

![image](https://user-images.githubusercontent.com/35171930/103022772-76654700-456e-11eb-9ede-58035707f2ad.png)

After investigating, I came to know that lib is consuming the package source directly, instead of the built package. Don't know how to resolve this issue. Can you please publish a compiled version of this dependency?

**Comment by sergiop** [comment]
Hi @Asif-chohan this library is based on [NWB](https://github.com/insin/nwb) and CSS Modules depends on it. I need to dig a little into the issue testing the library with Next.js.

I found this, maybe it could help: https://github.com/martpie/next-transpile-modules/issues/95

**Comment by Asif-chohan** [comment]
Hi sergiop, 
Thanks for the response. I've applied [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) but the problem persists. I've also try @zeit/next-sass and @zeit/next-css but it is going to harm TailwindCSS that I've used for my project.

**Comment by sergiop** [comment]
@Asif-chohan I just published [version 1.5.4](https://www.npmjs.com/package/react-giphy-searchbox/v/1.5.4) that fix the issue. Let me know if now you can use this component on your project. 😉
